### ISSUE TITLE
Consider Python packaging?

### ISSUE THREAD

**Issue by danghai** [keon/algorithms#264]

**Comment by keon** [comment]
I started this repo with the educational purpose, but I think this could be a potential direction for development.
in order to do this, we need to
- make docs for using api
- package and publish in pypi

I found `algorithms` is already in pypi, but it is not maintained (https://github.com/nryoung/algorithms).
It is actually pointing to our repo. Maybe I could reach out and talk.

**Comment by danghai** [comment]
@keon Awesome!, lets package them locally first. I create the PR for this: #268. But it has some issues. And you can reach out and talk about pypi with them. After local package works fine. We will push everything on pypi.

**Comment by danghai** [comment]
It works for python packaging locally. I merge them in repo. Lets check `README`, let me know if you have any errors

**Comment by keon** [comment]
shouldn't the api be something like:

`from algorithms.sort import merge_sort`?

we do not want to overwrite python's native api

**Comment by danghai** [comment]
@keon Yeah it is my mistake. But in order to do it, we need to group all source file under `algorithms` folder. What do you think?

**Comment by danghai** [comment]
@goswami-rahul do you know how to handle it :) ?

**Comment by keon** [comment]
I'll get back to this in a week. My feet is on fire right now :fire:

**Comment by keon** [comment]
Thanks to Nic(@nryoung), we are live in PyPI!
He also agreed to join us as one of the maintainers, so please welcome!
now you can install the package with simple command `pip install algorithms`.

**Comment by goswami-rahul** [comment]
Cheers! :)
