### ISSUE TITLE
Plan for testing

### ISSUE THREAD

**Issue by mingrammer** [keon/algorithms#29]
I want to add some additional matrix algorithms and some tests for that. 

So, do you have a testing plan of test format, rules of in/output example data, test script name and others?

**Comment by barrey11** [comment]
tell methe details.

**Comment by mingrammer** [comment]
Well, I want to know following for writing test codes

How can I write the tests for some algorithms? Where? How? There are some rules? See example,
```python
# Algorithm logic

if __name__ == '__main__':
    test_case = ...
    assert algo(test_case) == expected_result    
```
or
```python
# In this case, how many test cases are needed?
# Algorithm logic

if __name__ == '__main__':
    test_cases = [...]
    for test in test_cases:
        assert algo(test_case) == expected_result    
```
or
```python
# This is test script named algo_test.py
import unittest
import algo

class SomeAlgoTest(...):
    def setUp(self):
        # set up code

    def tearDown(sef):
        # tear down code

    def test_some_algo(self):
        # declare some test cases and expected results
        # test logics
```

And how can I run the tests for all algorithms?

**Comment by keon** [comment]
I think people should be able to run the algorithm using the implementation file. This is because we want people to learn and test algorithm with the minimalistic approach. But those simple tests cannot test the algorithm properly. So I suggest we put 4~5 simple tests in `__main__` and more extensive tests in the separate file. For now, we only have `__main__` (some don't even have it).

**Comment by mingrammer** [comment]
@keon  Thanks for giving a suggestion. I'll use that way as following

```python
if __name__ == '__main__':
    test_cases = [
        {
            'input': <test_input_instance>,
            'expected': <expected_value_instance>,
        },
        ...
    ]

    for test in test_cases:
        assert algo(test['input']) == test['expected']
```

**Comment by keon** [comment]
@mingrammer 
that's a good idea!

**Comment by jprojs** [comment]
I think we must use assert function (TDD) with some tests for this purpose

**Comment by Aluriak** [comment]
A good way to go could be to have dedicated `test_*.py` files in each directory.
It keeps the simplicity in source files, but allow one to expose more complete testing suite for an algorithm.
This last point is IMHO an important feature, mostly because it could provide a much more complete set of living examples, showing both general and corner cases to those who are interested in.

I'm a big fan of [`pytest`](http://pytest.org), which provides a very simple API (it just use the regular `assert` statement), and yet a complete output. Your testing code, @mingrammer, will not change, but will be moved into a dedicated function.
Unless you need very specific features of another overlay of stdlib's unittest, pytest is a good way to keep tests simple.

**Comment by delirious-lettuce** [comment]
@Aluriak ,

`pytest` is a great idea.

One of the issues with using regular `assert` statements (without `pytest`) is that as soon as one test fails, any other tests below it will not run. This is also the case where multiple unittests are run in a for loop (as shown by @mingrammer 's example `for test in tests`).

`@pytest.mark.parametrize` can help with that because it will run all the tests and report back whether they passed or failed.

**Comment by keon** [comment]
`doctest` seems to be another great option we have.
https://docs.python.org/3.5/library/doctest.html

**Comment by mingrammer** [comment]
keon want to keep the tests in the implementation files, but if we use `pytest`, we should use test files. So, .. I'm little a bit confused because I've never used both them: `pytest` and `doctest`. Which is better in our case? Any ideas?

**Comment by keon** [comment]
@mingrammer @delirious-lettuce
What do you think is better? I don't have experience in using Python for testing.
But I vote for `docstring` since it keeps all our implementation + test in one file for an algorithm.

**Comment by Aluriak** [comment]
Doctest and pytest are often used together.

Take for instance this repository : some tests are pushed behind the `if __name__ == '__main__':` line. This is not really the good place for it in more complex architectures, because sometimes imports needs the module to be deep into a package. The main script can't therefore be run as a standalone.
(and, in this case of the repo, the user have to perform the verifications by itself)

Moreover, if multiple functions are present in the module, the main will be quite overcrowed. If someone search for a usage example of some function, it will have to look for it in a constantly growing main.

So here is the doctest rationale : provides testing facility inside the module, at the closer spot to tested code : inside the docstring. This have one other major convenience : there is function usage examples inside the generated documentation, that are garanteed to works as long as unit tests are ok.

IMHO, any project could get a real interest into using doctest, even in its simpler form. In the end, it is just a way to format the usage example that allow automatic verification of both code and examples, which is priceless when you work with a living code base.

Pytest, on the other hand, is like any testing framework : useful when you need to produce deep tests on your project. In this repository, it's maybe not necessary for all algorithms, but, as i said earlier, you may need to show some obscure cases, and a dedicated file for that keeps the sources clean.

**Comment by mingrammer** [comment]
Ok, I'll use the doctest first for my PR. Thanks for with conversation!

**Comment by JacobIRR** [comment]
@keon Let me know if there is a concrete idea of what the testing should look like. I just did a file (kth_to_last) in the linkedlist dir and I think the whole dir would benefit from a dedicated test file.

**Comment by christianbender** [comment]
I added a unittest to the [bomb_enemy.py](https://github.com/keon/algorithms/blob/master/matrix/bomb_enemy.py).  
I can do this for other files, if it welcome.

**Comment by keon** [comment]
@christianbender that'd be awesome :)
