### ISSUE TITLE
remove the coverall tests

### ISSUE THREAD

**Issue by goswami-rahul** [keon/algorithms#328]
The Coverage tests by coverall create confusion among the contributors. I think this test give less information (I didn't find its results helpful any of the time, don't know if I was missing something) about the PR, and create more confusion among the contributors (most of the times they fail recently). I suggest we remove this test plugin? What do you think @keon @danghai ??

**Comment by danghai** [comment]
@goswami-rahul the reason why it always is failed because I only put the coveralls in `tests` folder. It only report the coverall in `tests` folder. I make the new PR #323 ( coverall for both 2 folder `tests` and `algorithms`). It will increase if someone add more test case for these files that do not have test.
